### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by manabreak** [hugorut/neural-cli#3] opened 2016-11-06 09:10 UTC
I tried to run `neural-cli train ./x.csv ./y.csv --normalize=true --verbose=true` with a simple set of training data and expected outputs, but I get the following error:

```
12.4131972238                    Traceback (most recent call last):
  File "/home/harri/Documents/neural-cli/bin/neuralcli", line 11, in <module>
    sys.exit(main())
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/neuralcli/cli.py", line 34, in train
    nn.train(verbose=verbose, save=output)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/neuralcli/neuralnet.py", line 127, in train
    method='TNC', jac=True, options={'maxiter': self.maxiter})
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 453, in minimize
    **options)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/scipy/optimize/tnc.py", line 409, in _minimize_tnc
    xtol, pgtol, rescale, callback)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/scipy/optimize/tnc.py", line 371, in func_and_grad
    f = fun(x, *args)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/neuralcli/neuralnet.py", line 270, in fit
    yt = y[t,:]
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/numpy/matrixlib/defmatrix.py", line 318, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: index 1 is out of bounds for axis 0 with size 1
```

The `x.csv` is like this:

```
a,b
1,1
1,2
1,3
1,4
1,5
2,1
2,2
2,3
2,4
2,5
2,6
3,1
3,2
3,3
3,4
3,5
3,6
```

And the y.csv is like this:

```
result
2
3
4
5
6
3
4
5
6
7
8
4
5
6
7
8
9
```

**Comment by hugorut** [comment] 2016-11-06 09:19
hi there, thanks for bringing this up. So this is technically not a bug but purely a poor explanation on my part in the documentation, which I will update after this issue is resolved. The result csv set should never be simply one column but a [one-hot](https://en.wikipedia.org/wiki/One-hot) encoded csv set. For example the first row of your result csv set is currently `2`, instead it should look as such:

| result_1 | result_2 | result_3 |
|----------|----------|----------|
| 0        | 1        | 0        |

For a better example of how the datasets should look please look at the example training set included in the repo [input_set](https://github.com/hugorut/neural-cli/blob/master/neuralcli/train.csv), [result_set](https://github.com/hugorut/neural-cli/blob/master/neuralcli/expected.csv)

**Comment by hugorut** [comment] 2016-11-06 09:20
Thanks for brining this to my attention, the cli tool should fail gracefully at this point however and give more verbose output to point users in the correct direction.

**Comment by manabreak** [comment] 2016-11-06 09:22
Ah, thanks for this info! I was actually wondering what the format should actually be in the input and the expected results. :)

**Comment by hugorut** [comment] 2016-11-06 09:26
No problem, please let me know if you have any more issues after reformatting the expectation set in the above way.

**Comment by manabreak** [comment] 2016-11-06 09:33
I got the training working by changing the expected output. Now, the predict doesn't seem to accept my inputs. When I try to run:

    neuralcli predict ./input.csv ./weights.csv 4

...the result I get is:

    Usage: neuralcli predict <options> X LABELS PARAMS
    Error: Invalid value for "labels": ./weights.csv is not a valid integer

Is this a problem in my call, or is there something wonky with the params handling? If I understood correctly, it tries to take the `./weights.csv` part as the `labels` argument.

**Comment by hugorut** [comment] 2016-11-06 09:39
no sorry mana, this is my fault for not making it more clear it should be:

```
neuralcli predict ./input.csv 4 ./weights.csv
```

as the labels refers to the the size of the output layer that the parameters were on. So for example if your result.csv had `10` columns this should be `10`

more info can be found by running `--help` with each command. With the following `predict` command it should give you an output similar to below.

```
Usage: neuralcli predict <options> X LABELS PARAMS

  predict an output with a given row. Prints the index of the prediction of
  the output row.

  Arguments:

      [x] the file that holds the 1 * n row example that should be predicted

      [labels] the size of the output layer that the parameters were trained
      on

      [params] the file that holds a 1 * n rolled parameter vector

Options:
  --sizeh INTEGER      the size of the hidden layer that the parameters were
                       trained on
  --normalize BOOLEAN  Perform normalization on the training set [default
                       false]
  --help               Show this message and exit.
```

**Comment by manabreak** [comment] 2016-11-06 11:02
Ah. The readme showed the arguments in the order I tried.

**Comment by hugorut** [comment] 2016-11-06 11:05
ah sorry, will change

**Comment by manabreak** [comment] 2016-11-06 11:11
Okay, so, trying to run the `predict` command with:

    neuralcli predict test.csv 4 weights.csv

I get an error:

```
Traceback (most recent call last):
  File "/home/harri/Documents/neural-cli/bin/neuralcli", line 11, in <module>
    sys.exit(main())
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/neuralcli/cli.py", line 66, in predict
    writer.write(nn.predict(x))
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/neuralcli/neuralnet.py", line 336, in predict
    theta1, theta2 = self.reshape_theta(self.params)
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/neuralcli/neuralnet.py", line 197, in reshape_theta
    theta2 = np.matrix(np.reshape(params[self.hidden_size * (self.input_size + 1):], (self.num_labels, (self.hidden_size + 1))))
  File "/home/harri/Documents/neural-cli/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 224, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged

```

The input of the train set had two columns, the output had four. The test.csv has only one line:

    3,3

And the weights.csv is from the training run.

**Comment by hugorut** [comment] 2016-11-06 11:12
hmm can you upload both your training and result set please, I'll debug my side

**Comment by manabreak** [comment] 2016-11-06 11:16
I made a [gist](https://gist.github.com/manabreak/0ee81547945d8d47c6ad3345796b9ee1) with all the files. To re-iterate: `x.csv` is the training set input, `y.csv` is the training set expected result. `weights.csv` is the result of the training, and `test.csv` is the input for the prediction.

**Comment by hugorut** [comment] 2016-11-06 11:18
thanks, I will look into this now, thank you for your patience

**Comment by hugorut** [comment] 2016-11-06 11:21
right managed to replicate the issue, I'm tracking down the problem now

**Comment by hugorut** [comment] 2016-11-06 11:34
found the issue, going to push change repackage and then you should be able to download the new version which will be working

**Comment by hugorut** [comment] 2016-11-06 11:42
ok this is fixed with version [1.6](https://github.com/hugorut/neural-cli/releases/tag/1.6) please reinstall neuralcli:

```
pip uninstall neuralcli
pip install neuralcli
```

let me know if that fixes the bug, I will then close issue

**Comment by manabreak** [comment] 2016-11-06 17:39
Sorry for the delay. Tried the updated version, and got it working. You can close this. Thanks!

**Comment by hugorut** [comment] 2016-11-06 17:58
great news!

![](https://media.giphy.com/media/Wi7QlqrOHYJJm/giphy.gif)

**Closed** 2016-11-06 17:58 UTC
Labels: bug, error handling, help wanted
